CMTPATH=/afs/ihep.ac.cn/users/y/yiph/sniper/junosw:/home/bes/zoujh/scratchfs/sniper/junosw:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/offline:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/sniper:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalInterface
CMT_tag=$(tag)
CMTROOT=/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/CMT/v1r26
CMT_root=/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/CMT/v1r26
CMTVERSION=v1r26
CMT_offset=/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs
cmt_hardware_query_command=uname -m
cmt_hardware=`$(cmt_hardware_query_command)`
cmt_system_version_query_command=${CMTROOT}/mgr/cmt_linux_version.sh | ${CMTROOT}/mgr/cmt_filter_version.sh
cmt_system_version=`$(cmt_system_version_query_command)`
cmt_compiler_version_query_command=${CMTROOT}/mgr/cmt_gcc_version.sh | ${CMTROOT}/mgr/cmt_filter3_version.sh
cmt_compiler_version=`$(cmt_compiler_version_query_command)`
PATH=/afs/ihep.ac.cn/users/y/yiph/sniper/junosw/InstallArea/${CMTCONFIG}/bin:/home/bes/zoujh/scratchfs/sniper/junosw/InstallArea/${CMTCONFIG}/bin:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/offline/InstallArea/${CMTCONFIG}/bin:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/sniper/InstallArea/${CMTCONFIG}/bin:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/CMT/v1r26/${CMTBIN}:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/mysql-connector-cpp/1.1.8/bin:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/mysql-connector-c/6.1.9/bin:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/libmore/0.8.3/bin:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/Geant4/9.4.p04/bin:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/HepMC/2.06.09/bin:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/ROOT/5.34.11/bin:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/CLHEP/2.1.0.1/bin:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/fftw3/3.2.1/bin:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/gsl/1.16/bin:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/Xercesc/3.1.1/bin:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/GCCXML/master/bin:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/Git/1.8.4.3/bin:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/Cmake/2.8.12.1/bin:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/Boost/1.55.0/bin:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/Python/2.7.6/bin:/afs/ihep.ac.cn/soft/common/sysgroup/hep_job/bin:/usr/lib64/qt-3.3/bin:/usr/kerberos/sbin:/usr/kerberos/bin:/bin:/usr/bin:/usr/externals/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin:/sbin:/usr/java/latest/bin:/opt/puppetlabs/bin:/home/bes/zoujh/bin
CLASSPATH=/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/CMT/v1r26/java
debug_option=-g
cc=gcc
ccomp=$(cc) -c $(includes) $(cdebugflags) $(cflags) $(pp_cflags)
clink=$(cc) $(clinkflags) $(cdebugflags)
ppcmd=-I
preproc=c++ -MD -c 
cpp=g++
cppflags=-O2 -fPIC -pipe -ansi -W -Wall -Wwrite-strings -Wpointer-arith -Woverloaded-virtual 
pp_cppflags=-D_GNU_SOURCE
cppcomp=$(cpp) -c $(includes) $(cppdebugflags) $(cppflags) $(pp_cppflags)
cpplink=$(cpp) $(cpplinkflags) $(cppdebugflags)
for=g77
fflags=$(debug_option)
fcomp=$(for) -c $(fincludes) $(fflags) $(pp_fflags)
flink=$(for) $(flinkflags)
javacomp=javac -classpath $(src):$(CLASSPATH) 
javacopy=cp
jar=jar
X11_cflags=-I/usr/include
Xm_cflags=-I/usr/include
X_linkopts=-L/usr/X11R6/lib -lXm -lXt -lXext -lX11 -lm
lex=lex $(lexflags)
yaccflags= -l -d 
yacc=yacc $(yaccflags)
ar=ar cr
ranlib=ranlib
make_shlib=${CMTROOT}/mgr/cmt_make_shlib_common.sh extract
shlibsuffix=so
shlibbuilder=g++ $(cmt_installarea_linkopts) 
shlibflags=-shared
symlink=/bin/ln -fs 
symunlink=/bin/rm -f 
library_install_command=python $(SniperPolicy_root)/cmt/fragments/install.py -xCVS -x.svn -x*~ -x*.stamp -s --log=./install.history 
build_library_links=$(cmtexe) build library_links -tag=$(tags)
remove_library_links=$(cmtexe) remove library_links -tag=$(tags)
cmtexe=${CMTROOT}/${CMTBIN}/cmt.exe
build_prototype=$(cmtexe) build prototype
build_dependencies=$(cmtexe) -tag=$(tags) build dependencies
build_triggers=$(cmtexe) build triggers
format_dependencies=${CMTROOT}/mgr/cmt_format_deps.sh
implied_library_prefix=-l
SHELL=/bin/sh
q="
src=../src/
doc=../doc/
inc=../src/
mgr=../cmt/
application_suffix=.exe
library_prefix=lib
unlock_command=rm -rf 
lock_name=cmt
lock_suffix=.lock
lock_file=${lock_name}${lock_suffix}
svn_checkout_command=python ${CMTROOT}/mgr/cmt_svn_checkout.py 
gmake_hosts=lx1 rsplus lxtest as7 dxplus ax7 hp2 aleph hp1 hpplus papou1-fe atlas
make_hosts=virgo-control1 rio0a vmpc38a
everywhere=hosts
install_command=python $(SniperPolicy_root)/cmt/fragments/install.py -xCVS -x.svn -x*~ -x*.stamp --log=./install.history 
uninstall_command=python $(SniperPolicy_root)/cmt/fragments/install.py -u --log=./install.history 
cmt_installarea_command=python $(SniperPolicy_root)/cmt/fragments/install.py -xCVS -x.svn -x*~ -x*.stamp -s --log=./install.history 
cmt_uninstallarea_command=/bin/rm -f 
cmt_install_area_command=$(cmt_installarea_command)
cmt_uninstall_area_command=$(cmt_uninstallarea_command)
cmt_install_action=$(CMTROOT)/mgr/cmt_install_action.sh
cmt_installdir_action=$(CMTROOT)/mgr/cmt_installdir_action.sh
cmt_uninstall_action=$(CMTROOT)/mgr/cmt_uninstall_action.sh
cmt_uninstalldir_action=$(CMTROOT)/mgr/cmt_uninstalldir_action.sh
mkdir=mkdir
cmt_cvs_protocol_level=v1r1
cmt_installarea_prefix=InstallArea
CMT_PATH_remove_regexp=/[^/]*/
CMT_PATH_remove_share_regexp=/share/
NEWCMTCONFIG=x86_64-sl69-gcc447
SamplingSvc_tag=$(tag)
SAMPLINGSVCROOT=/afs/ihep.ac.cn/users/y/yiph/sniper/junosw/SamplingSvc
SamplingSvc_root=/afs/ihep.ac.cn/users/y/yiph/sniper/junosw/SamplingSvc
SAMPLINGSVCVERSION=v0
SamplingSvc_cmtpath=/afs/ihep.ac.cn/users/y/yiph/sniper/junosw
SamplingSvc_project=junosw
SniperKernel_tag=$(tag)
SNIPERKERNELROOT=/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/sniper/SniperKernel
SniperKernel_root=/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/sniper/SniperKernel
SNIPERKERNELVERSION=v2
SniperKernel_cmtpath=/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/sniper
SniperKernel_project=sniper
SniperPolicy_tag=$(tag)
SNIPERPOLICYROOT=/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/sniper/SniperPolicy
SniperPolicy_root=/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/sniper/SniperPolicy
SNIPERPOLICYVERSION=v0
SniperPolicy_cmtpath=/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/sniper
SniperPolicy_project=sniper
libraryshr_linkopts=-fPIC -ldl -Wl,--as-needed -Wl,--no-undefined 
application_linkopts=-Wl,--export-dynamic 
BINDIR=$(tag)
remove_command=$(cmt_uninstallarea_command)
Boost_tag=$(tag)
BOOSTROOT=/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalInterface/Externals/Boost
Boost_root=/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalInterface/Externals/Boost
BOOSTVERSION=v0
Boost_cmtpath=/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalInterface
Boost_offset=Externals
Boost_project=ExternalInterface
Python_tag=$(tag)
PYTHONROOT=/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalInterface/Externals/Python
Python_root=/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalInterface/Externals/Python
PYTHONVERSION=v0
Python_cmtpath=/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalInterface
Python_offset=Externals
Python_project=ExternalInterface
Python_linkopts= `pkg-config --libs python` 
Python_cppflags= `pkg-config --cflags python` 
Boost_home=${JUNO_EXTLIB_Boost_HOME}
Boost_linkopts= -L$(Boost_home)/lib  -lboost_python 
includes= $(ppcmd)"$(SamplingSvc_root)"  $(ppcmd)"$(srcdir)" $(ppcmd)"/home/bes/zoujh/scratchfs/sniper/junosw/InstallArea/include" $(ppcmd)"/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/offline/InstallArea/include" $(ppcmd)"/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/sniper/InstallArea/include" $(use_includes)
PYTHONPATH=/afs/ihep.ac.cn/users/y/yiph/sniper/junosw/InstallArea/python:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/offline/InstallArea/python:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/sniper/InstallArea/python:/afs/ihep.ac.cn/users/y/yiph/sniper/junosw/InstallArea/amd64_linux26/lib:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/offline/InstallArea/amd64_linux26/lib:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/sniper/InstallArea/amd64_linux26/lib:/home/bes/zoujh/scratchfs/sniper/junosw/InstallArea/python:/home/bes/zoujh/scratchfs/sniper/junosw/InstallArea/amd64_linux26/lib:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/ROOT/5.34.11/lib:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/Python/2.7.6/lib/./python2.7/lib-dynload:/usr/lib64/python
SniperKernel_linkopts= -lSniperKernel  -lSniperPython 
SniperKernel_stamps=${SNIPERKERNELROOT}/${BINDIR}/SniperPython.stamp 
SniperKernel_linker_library=SniperPython
SniperPython_dependencies=SniperKernel
SniperPython_shlibflags= -lSniperKernel 
SamplingSvc_linkopts= -lPyROOT  -ldl  -lSamplingSvc 
SamplingSvc_shlibflags=$(libraryshr_linkopts) $(cmt_installarea_linkopts) $(SamplingSvc_use_linkopts)
SamplingSvc_use_linkopts=    $(SniperKernel_linkopts)  $(SniperPolicy_linkopts)  $(Boost_linkopts)  $(Python_linkopts) 
SamplingSvc_stamps=${SAMPLINGSVCROOT}/${BINDIR}/SamplingSvc.stamp 
SamplingSvc_linker_library=SamplingSvc
tag=amd64_linux26
package=SamplingSvc
version=v0
PACKAGE_ROOT=$(SAMPLINGSVCROOT)
srcdir=../src
bin=../$(SamplingSvc_tag)/
javabin=../classes/
mgrdir=cmt
BIN=/afs/ihep.ac.cn/users/y/yiph/sniper/junosw/SamplingSvc/amd64_linux26/
project=junosw
cmt_installarea_paths= $(cmt_installarea_prefix)/$(CMTCONFIG)/bin $(sniper_installarea_prefix)/$(CMTCONFIG)/lib $(sniper_installarea_prefix)/share/lib $(sniper_installarea_prefix)/share/bin $(offline_installarea_prefix)/$(CMTCONFIG)/lib $(offline_installarea_prefix)/share/lib $(offline_installarea_prefix)/share/bin $(junosw_installarea_prefix)/$(CMTCONFIG)/lib $(junosw_installarea_prefix)/share/lib $(junosw_installarea_prefix)/share/bin $(junosw_installarea_prefix)/$(CMTCONFIG)/lib $(junosw_installarea_prefix)/share/lib $(junosw_installarea_prefix)/share/bin
use_linkopts= $(cmt_installarea_linkopts)   $(SamplingSvc_linkopts)  $(SniperKernel_linkopts)  $(SniperPolicy_linkopts)  $(Boost_linkopts)  $(Python_linkopts) 
ExternalInterface_installarea_prefix=$(cmt_installarea_prefix)
ExternalInterface_installarea_prefix_remove=$(ExternalInterface_installarea_prefix)
LD_LIBRARY_PATH=/afs/ihep.ac.cn/users/y/yiph/sniper/junosw/InstallArea/${CMTCONFIG}/lib:/home/bes/zoujh/scratchfs/sniper/junosw/InstallArea/${CMTCONFIG}/lib:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/offline/InstallArea/${CMTCONFIG}/lib:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/sniper/InstallArea/${CMTCONFIG}/lib:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/mysql-connector-cpp/1.1.8/lib:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/mysql-connector-c/6.1.9/lib:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/libmore/0.8.3/lib:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/Geant4/9.4.p04/lib/geant4-9.4.4/Linux-g++:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/CLHEP/2.1.0.1/lib:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/Geant4/9.4.p04/lib:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/HepMC/2.06.09/lib:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/ROOT/5.34.11/lib:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/fftw3/3.2.1/lib:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/gsl/1.16/lib:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/Xercesc/3.1.1/lib:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/Git/1.8.4.3/lib64:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/Git/1.8.4.3/lib:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/Boost/1.55.0/lib:/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/Python/2.7.6/lib:/usr/lib64/classads:/usr/lib64:/usr/lib
sniper_installarea_prefix=$(cmt_installarea_prefix)
sniper_installarea_prefix_remove=$(sniper_installarea_prefix)
offline_installarea_prefix=$(cmt_installarea_prefix)
offline_installarea_prefix_remove=$(offline_installarea_prefix)
junosw_installarea_prefix=$(cmt_installarea_prefix)
junosw_installarea_prefix_remove=$(junosw_installarea_prefix)
cmt_installarea_linkopts= -L/afs/ihep.ac.cn/users/y/yiph/sniper/junosw/$(junosw_installarea_prefix)/$(CMTCONFIG)/lib  -L/home/bes/zoujh/scratchfs/sniper/junosw/$(junosw_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/offline/$(offline_installarea_prefix)/$(CMTCONFIG)/lib  -L/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/sniper/$(sniper_installarea_prefix)/$(CMTCONFIG)/lib 
ExternalInterface_home=/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalInterface
sniper_home=/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/sniper
offline_home=/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/offline
junosw_home=/afs/ihep.ac.cn/users/y/yiph/sniper/junosw
junosw_install_include= /home/bes/zoujh/scratchfs/sniper/junosw/$(junosw_installarea_prefix)/include 
offline_install_include= /afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/offline/$(offline_installarea_prefix)/include 
sniper_install_include= /afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/sniper/$(sniper_installarea_prefix)/include 
sniper_python_path=/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/sniper/$(sniper_installarea_prefix)/$(tag)/lib
offline_python_path=/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/offline/$(offline_installarea_prefix)/$(tag)/lib
junosw_python_path=/afs/ihep.ac.cn/users/y/yiph/sniper/junosw/$(junosw_installarea_prefix)/$(tag)/lib
sniper_install_python=/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/sniper/$(sniper_installarea_prefix)/python
offline_install_python=/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/offline/$(offline_installarea_prefix)/python
junosw_install_python=/afs/ihep.ac.cn/users/y/yiph/sniper/junosw/$(junosw_installarea_prefix)/python
CMTINSTALLAREA=/afs/ihep.ac.cn/users/y/yiph/sniper/junosw/$(cmt_installarea_prefix)
use_requirements=requirements $(CMT_root)/mgr/requirements $(SniperKernel_root)/cmt/requirements $(SniperPolicy_root)/cmt/requirements $(Boost_root)/cmt/requirements $(Python_root)/cmt/requirements 
use_includes= $(ppcmd)"$(SniperKernel_root)/src" $(ppcmd)"$(SniperPolicy_root)/src" $(ppcmd)"/afs/ihep.ac.cn/soft/juno/JUNO-ALL-SLC6/Release/J17v1r1/ExternalLibs/Boost/1.55.0/include" $(ppcmd)"$(Python_root)/src" 
use_fincludes= $(use_includes)
use_stamps=  $(SamplingSvc_stamps)  $(SniperKernel_stamps)  $(SniperPolicy_stamps)  $(Boost_stamps)  $(Python_stamps) 
use_cflags=  $(SamplingSvc_cflags)  $(SniperKernel_cflags)  $(SniperPolicy_cflags)  $(Boost_cflags)  $(Python_cflags) 
use_pp_cflags=  $(SamplingSvc_pp_cflags)  $(SniperKernel_pp_cflags)  $(SniperPolicy_pp_cflags)  $(Boost_pp_cflags)  $(Python_pp_cflags) 
use_cppflags=  $(SamplingSvc_cppflags)  $(SniperKernel_cppflags)  $(SniperPolicy_cppflags)  $(Boost_cppflags)  $(Python_cppflags) 
use_pp_cppflags=  $(SamplingSvc_pp_cppflags)  $(SniperKernel_pp_cppflags)  $(SniperPolicy_pp_cppflags)  $(Boost_pp_cppflags)  $(Python_pp_cppflags) 
use_fflags=  $(SamplingSvc_fflags)  $(SniperKernel_fflags)  $(SniperPolicy_fflags)  $(Boost_fflags)  $(Python_fflags) 
use_pp_fflags=  $(SamplingSvc_pp_fflags)  $(SniperKernel_pp_fflags)  $(SniperPolicy_pp_fflags)  $(Boost_pp_fflags)  $(Python_pp_fflags) 
use_libraries= $(SniperKernel_libraries)  $(SniperPolicy_libraries)  $(Boost_libraries)  $(Python_libraries) 
fincludes= $(includes)
SamplingSvc_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
install_more_includes_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
SamplingSvc_python_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
make_GUID={88BF15AB-5A2D-4bea-B64F-02752C2A1F4F}
constituents= SamplingSvc install_more_includes SamplingSvc_python 
all_constituents= $(constituents)
constituentsclean= SamplingSvc_pythonclean install_more_includesclean SamplingSvcclean 
all_constituentsclean= $(constituentsclean)
cmt_actions_constituents= make 
cmt_actions_constituentsclean= makeclean 
SamplingSvcprototype_dependencies= $(SamplingSvccompile_dependencies)
